<?php
    include "autoform.php";
    $autoform = array(
        array(
            "name" => "nombre",
            "type" => "text",
            "label" => "Nombre",
            "required" => true,
            "minlength" => 3,
            "maxlength" => 20,
            "placeholder" => "Introduce tu nombre",
            "value"=>  "pepe",
            "id" => "nombre",
        ),
        array(
            "name" => "nombre",
            "type" => "text",
            "label" => "Nombre",
            "required" => true,
            "minlength" => 3,
            "maxlength" => 20,
            "placeholder" => "Introduce tu nombre",
            "value"=>  "pepe",
            "id" => "nombre",
        ),
        array(
            "name" => "nombre",
            "type" => "text",
            "label" => "Nombre",
            "required" => true,
            "minlength" => 3,
            "maxlength" => 20,
            "placeholder" => "Introduce tu nombre",
            "value"=>  "pepe",
            "id" => "nombre",
        ),
        array(
            "name" => "nombre",
            "type" => "text",
            "label" => "Nombre",
            "required" => true,
            "minlength" => 3,
            "maxlength" => 20,
            "placeholder" => "Introduce tu nombre",
            "value"=>  "pepe",
            "id" => "nombre",
        ),
        array(
            "name" => "nombre",
            "type" => "text",
            "label" => "Nombre",
            "required" => true,
            "minlength" => 3,
            "maxlength" => 20,
            "placeholder" => "Introduce tu nombre",
            "value"=>  "pepe",
            "id" => "nombre",
        ),
    );
    autoform($autoform);
?>